## Generated from D:/ZYNQ/lasercom/lasercom_top/Sei_Pin.xdc
## Scope: sys_clk and CAM A pins only.
## Old hierarchical get_nets constraints and unrelated SDI/UART/CAM B pins are intentionally omitted.

create_clock -period 10.000 -name SYS_clk_100M -waveform {0.000 5.000} -add [get_ports sys_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property PACKAGE_PIN AE5 [get_ports sys_clk_p]
set_property PACKAGE_PIN AF5 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS [get_ports sys_clk_n]
create_clock -period    3.472   [get_ports i_lvds_clk_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_clk_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_clk_n]
set_property PACKAGE_PIN D7  [get_ports i_lvds_clk_p]
set_property PACKAGE_PIN D6  [get_ports i_lvds_clk_n]
set_property IOSTANDARD LVDS [get_ports i_lvds_sync_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_sync_n]
set_property PACKAGE_PIN A9  [get_ports i_lvds_sync_p]
set_property PACKAGE_PIN A8  [get_ports i_lvds_sync_n]
set_property IOSTANDARD LVDS [get_ports i_lvds_data0_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_data0_n]
set_property PACKAGE_PIN B5  [get_ports i_lvds_data0_p]
set_property PACKAGE_PIN A5  [get_ports i_lvds_data0_n]
set_property IOSTANDARD LVDS [get_ports i_lvds_data1_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_data1_n]
set_property PACKAGE_PIN C6  [get_ports i_lvds_data1_p]
set_property PACKAGE_PIN B6  [get_ports i_lvds_data1_n]
set_property IOSTANDARD LVDS [get_ports i_lvds_data2_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_data2_n]
set_property PACKAGE_PIN A7  [get_ports i_lvds_data2_p]
set_property PACKAGE_PIN A6  [get_ports i_lvds_data2_n]
set_property IOSTANDARD LVDS [get_ports i_lvds_data3_p]
set_property IOSTANDARD LVDS [get_ports i_lvds_data3_n]
set_property PACKAGE_PIN C8  [get_ports i_lvds_data3_p]
set_property PACKAGE_PIN B8  [get_ports i_lvds_data3_n]
set_property PACKAGE_PIN F7  [get_ports spi_sck ]
set_property PACKAGE_PIN E5  [get_ports spi_ss_n]
set_property PACKAGE_PIN F6  [get_ports spi_mosi]
set_property PACKAGE_PIN G8  [get_ports spi_miso]
set_property IOSTANDARD LVCMOS18 [get_ports spi_sck ]
set_property IOSTANDARD LVCMOS18 [get_ports spi_ss_n]
set_property IOSTANDARD LVCMOS18 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports spi_miso]
set_property PACKAGE_PIN E9  [get_ports camera_reset_n ]
set_property PACKAGE_PIN D15 [get_ports camera_vdd_18_en]
set_property PACKAGE_PIN D14 [get_ports camera_vdd_33_en]
set_property PACKAGE_PIN D9  [get_ports camera_lvds_clk]
set_property PACKAGE_PIN G6  [get_ports trigger_0]
set_property IOSTANDARD LVCMOS18 [get_ports camera_reset_n ]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vdd_18_en]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vdd_33_en]
set_property IOSTANDARD LVCMOS18 [get_ports camera_lvds_clk]
set_property IOSTANDARD LVCMOS18 [get_ports trigger_0]
